# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.5.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: vaibhavspatre@gmail.com
author_name: maroti
contract_name: escrow_contract
deployment_language: python
preset_name: production
project_name: escrow_mechanism

